/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Variant({
  'driedGinger' : IDL.Null,
  'pickles' : IDL.Null,
  'driedVegetables' : IDL.Null,
  'driedGreenChillyPowder' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : Product,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminGetAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], []),
  'adminGetInquiriesByProduct' : IDL.Func([Product], [IDL.Vec(Inquiry)], []),
  'getProductList' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Product],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Variant({
    'driedGinger' : IDL.Null,
    'pickles' : IDL.Null,
    'driedVegetables' : IDL.Null,
    'driedGreenChillyPowder' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : Product,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'adminGetAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], []),
    'adminGetInquiriesByProduct' : IDL.Func([Product], [IDL.Vec(Inquiry)], []),
    'getProductList' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Product],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };